import re


def clean_text(text: str) -> str:
    """
    Cleans a given text string by removing formatting, markdown, emojis, and other
    symbols commonly generated by large language models (LLMs).

    Args:
        text: The input text to be cleaned.

    When synthesizing LLM output to speech, the synthesis will also pronounce
    formatting, emojis, and other symbols, resulting in unnatural or confusing audio.
    Cleaning the text ensures the synthesized speech is clear and natural.
    """
    # Remove math blocks and dollar signs
    text = re.sub(r"\$\$.*?\$\$", "", text, flags=re.DOTALL)  # remove $$ math $$
    text = re.sub(r"\$(.*?)\$", r"\1", text)  # unwrap $x$ but remove the $ characters
    text = text.replace("$", "")  # remove any remaining $

    # Remove markdown formatting
    text = re.sub(r"(\*\*\*|\*\*|\*|__|_|~~|`+)", "", text)

    # Remove blockquote markers
    text = re.sub(r"^>\s?", "", text, flags=re.MULTILINE)

    # Remove markdown headers (e.g. ## Title)
    text = re.sub(r"^#{1,6}\s*", "", text, flags=re.MULTILINE)

    # Remove link URLs but keep anchor text
    text = re.sub(r"\[([^\]]+)\]\([^\)]+\)", r"\1", text)

    # Remove emojis and symbols (comprehensive)
    emoji_pattern = re.compile(
        "["
        "\U0001f1e6-\U0001f1ff"  # Regional Indicator Symbols
        "\U0001f300-\U0001f5ff"  # Symbols & Pictographs
        "\U0001f600-\U0001f64f"  # Emoticons
        "\U0001f680-\U0001f6ff"  # Transport & Map
        "\U0001f700-\U0001f77f"  # Alchemical
        "\U0001f780-\U0001f7ff"  # Geometric Ext
        "\U0001f800-\U0001f8ff"  # Supplemental Arrows-C
        "\U0001f900-\U0001f9ff"  # Supplemental Symbols & Pictographs
        "\U0001fa00-\U0001fa6f"  # Chess
        "\U0001fa70-\U0001faff"  # Symbols Extended-A
        "\U000024c2-\U0001f251"  # Enclosed characters (🅰️, 🅱️…)
        "\U00002702-\U000027bf"  # Dingbats (⭐ etc.)
        "\u2600-\u26ff"  # Misc Symbols (☀️…)
        "\ufe0f"  # Variation Selector
        "\u200d"  # Zero-width Joiner
        "]+",
        flags=re.UNICODE,
    )
    text = emoji_pattern.sub("", text)

    # Remove all * and # characters literally
    text = re.sub(r"[\*#]", "", text)

    text = re.sub(r"(^|\s)[-—-]{2,}(\s|$)", " ", text)

    # Optionally remove decorative horizontal rules (---, ***, etc)
    text = re.sub(r"^-{2,}|_{2,}|\*{2,}", "", text, flags=re.MULTILINE)

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text


def main() -> None:
    text = """
    # 🌟 **_The quick brown fox jumps over the
    lazy dog!_** 🦊💨🐶 > *Did you know?* > **This sentence contains every letter of
    the English alphabet!** 🅰️🅱️🆎🆑 --- - ✨ **Bold** - _*Italic*_ - `Monospace`
    - ~~Strikethrough~~ - [Learn more about pangrams!](https://en.wikipedia.org/wiki/Pangram)
    🌐 --- ## 🎉 **Let's break it down:** 1. **The quick brown fox** 🦊
    2. **jumps over** 💨 3. **the lazy dog!** 🐶 --- ## 🎨 **Fun with Math:** If $x$ =
    quickness of fox, and $y$ = laziness of dog: $$ \text{Speed Advantage} = x - y $$
    --- > ⭐️ _Isn't Markdown fun?_ ⭐️ --- If you want another sentence or style, just
    tell me! 🚀
    """
    cleaned_text = clean_text(text)
    print(cleaned_text)


if __name__ == "__main__":
    main()
